@startuml
actor dev as "Developer"

rectangle Database

rectangle "World System"{

    usecase UC1 as "Facilitate the creation of a city report"

    usecase UCa as "Generate city report"

    dev - UC1
    UC1 ..> UCa : include
    UC1 - Database

}

rectangle "Use case 2"{

    usecase UC2 as "Display a non-set list of countries"

    usecase UCb as "Display list"

    dev - UC2
    UC2 ..> UCb : include
    UC2 - Database

}
@enduml